// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Registrations.Models;

public partial class CarGpsData
{
    public DateTime Time { get; set; }

    public string CarId { get; set; }

    public double Latitude { get; set; }

    public double Longitude { get; set; }
}