// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Registrations.Models;

public partial class LookupRegistration
{
    public int Id { get; set; }

    public string Region { get; set; }
}