// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Registrations.Models;

public partial class PostgresContext : DbContext
{
    public PostgresContext(DbContextOptions<PostgresContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CarGpsData> CarGpsData { get; set; }

    public virtual DbSet<LookupRegistration> LookupRegistrations { get; set; }

    public virtual DbSet<Registration> Registrations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            //.HasPostgresEnum("regiont", new[] { "OTHER", "EU" })
            .HasPostgresExtension("timescaledb");

        modelBuilder.Entity<CarGpsData>(entity =>
        {
            entity.HasKey(e => new { e.CarId, e.Time }).HasName("car_gps_data_pkey");

            entity.ToTable("car_gps_data");

            entity.HasIndex(e => e.Time, "car_gps_data_time_idx").IsDescending();

            entity.Property(e => e.CarId)
                .HasMaxLength(8)
                .IsFixedLength()
                .HasColumnName("car_id");
            entity.Property(e => e.Time).HasColumnName("time");
            entity.Property(e => e.Latitude).HasColumnName("latitude");
            entity.Property(e => e.Longitude).HasColumnName("longitude");
        });

        modelBuilder.Entity<LookupRegistration>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("lookup_registration_pkey");

            entity.ToTable("lookup_registration");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Region)
                .HasMaxLength(8)
                .IsFixedLength()
                .HasColumnName("region");
        });

        modelBuilder.Entity<Registration>(entity =>
        {
            entity.HasKey(e => e.CarId).HasName("registration_pkey");

            entity.ToTable("registration");

            entity.Property(e => e.CarId)
                .HasMaxLength(8)
                .IsFixedLength()
                .HasColumnName("car_id");
            entity.Property(e => e.RegionId).HasColumnName("region_id");
        });
        modelBuilder.HasSequence("chunk_constraint_name", "_timescaledb_catalog");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}